### PR TITLE
fix/30-help-list: Adding reserved commands to devcmd

### LINKED ISSUE #30: "help" / "list" feature to see all devcmd tasks
There currently exists no "help" / "list" feature to see all devcmd tasks. To see all tasks, you have to navigate to the dev_cms folde.

The following approach would be desirable: 

- Type an command like this: `yarn devcmd help`
- Get an helpful output with the task names and maybe a short description. This can look for example like this: 
image

### PR DESCRIPTION
**Pull request by lieberlois**
This pull request (for issue #30 ) adds the option of using reserved commands to devcmd. Reserved commands can be any command that starts with "--". The reserved commands have to be started seperately from the devcmd-cli, since we 1) dont want devcmd to look for a "--help.ts" file and 2) dont want node to try and display the "node --help" output.

Examples:

image

### CODE REVIEW

File: packages/devcmd/src/utils/get_reserved_command.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { helpCmd, listCmd } from "../reserved-cmds";
```
Comment (lehnerpat) [inline packages/devcmd/src/utils/get_reserved_command.ts]: since we map the reserved commands explicitly anyway (instead of by file name or so, like we do regular tasks), I think this file (`get_reserved_command.ts`)would be better located in the `reserved-commands` directory :)

IMO then you also don't need to re-export all reserved commands in the `index.ts` because this file is probably the only one importing them, and it'll be located right besides them :)

File: packages/devcmd/src/utils/get_reserved_command.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+type CommandFn = () => Promise<void>;
+
+const CommandMapping: Record<string, CommandFn> = {
+  list: listCmd,
+  help: helpCmd,
+};
+
+export const reservedCommands = Object.keys(CommandMapping);
```
Comment (lehnerpat) [inline packages/devcmd/src/utils/get_reserved_command.ts]: very minor: you can use `Object.freeze()` to make this map and list immutable, preventing accidental modification (this isn't a big issue, it just prevents us from accidentally modifying this information in memory when we use it)

File: packages/devcmd/src/reserved-cmds/help.ts [hunk 3]
```diff
@@ -0,0 +1,10 @@
+import { bold, green } from "kleur/colors";
+import { reset } from "kleur";
+
+export async function helpCmd(): Promise<void> {
+  return new Promise((res) => {
```
Comment (lehnerpat) [inline packages/devcmd/src/reserved-cmds/help.ts]: when a function is `async`, you don't need to explicitly return a Promise, the content is wrapped in a Promise automatically (this is slightly obscured if you don't know about it, because `async` functions explicitly returning a Promise like here don't get wrapped again to produce a `Promise<Promise<void>>`).

you can just write:
```ts
export async function helpCmd(): Promise<void> {
    console.log(bold(green("Usage:")), reset("devcmd <task>"));
    console.log("Use", green("devcmd --list"), "to show available tasks.");
}
```

File: packages/devcmd/src/reserved-cmds/list.ts [hunk 4]
```diff
@@ -0,0 +1,27 @@
+import { readdir } from "fs";
```
Comment (lehnerpat) [inline packages/devcmd/src/reserved-cmds/list.ts]: you can `import { readdir } from "fs-extra";` (see [fs-extra](https://www.npmjs.com/package/fs-extra)), or `import { promises as fs } from "fs";` and use `fs.readdir` (see [Promises API of `fs`](https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_promises_api)), then you don't need to promisify it yourself :)

File: packages/devcmd/src/reserved-cmds/list.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+export async function listCmd(): Promise<void> {
+  const cwd = process.cwd();
+
+  try {
+    const files = await readdirPromise(cwd);
+
+    if (files.length > 0) {
+      console.log(bold(green("Available tasks:")));
+      files.sort().forEach((f) => {
```
Comment (lehnerpat) [inline packages/devcmd/src/reserved-cmds/list.ts]: I think we should filter this list -- it currently lists all files (and maybe even all directories?) even though devcmd can only run .ts and .js files.

However, for that we should also commonize the knowledge about supported file types and not duplicate it, so I think it's best to do that in a separate PR.
(i.e. feel free to create an issue for this and leave it as it is here :) )

File: packages/devcmd/src/reserved-cmds/list.ts [hunk 6]
```diff
@@ -0,0 +1,27 @@
+import { readdir } from "fs";
+import { promisify } from "util";
+import { bold, green } from "kleur/colors";
+import { red } from "kleur";
+
+const readdirPromise = promisify(readdir);
+
+export async function listCmd(): Promise<void> {
+  const cwd = process.cwd();
```
Comment (lehnerpat) [inline packages/devcmd/src/reserved-cmds/list.ts:8]: I think it's useful to tell the user in which directory exactly we're looking for tasks, i.e. print the absolute path of `cwd`.

I always find it frustrating when I'm accidentally running a program in the wrong directory and it doesn't do what I expect (e.g. tell me "No tasks available") but doesn't tell me where it looked.

File: packages/devcmd/src/from-cli/index.ts [hunk 7]
```diff
@@ -1,8 +1,10 @@
 import { promises as fs } from "fs";
+import { green } from "kleur";
 import { gray, bold, red, reset } from "kleur/colors";
 import { spawnSync } from "npm-run";
 import path from "path";
 import { formatCommandArgs, formatCommandName } from "../utils/format_utils";
+import { getReservedCommand, reservedCommands } from "../utils/get_reserved_command";
```
Comment (lehnerpat) [inline packages/devcmd/src/from-cli/index.ts]: is there a reason why we use both getReservedCommand and reservedCommands here?

I would expect the information to be a little more unified (either an exported immutable map of name to command function, or otherwise getReservedCommand being used to look up the requested command)

File: packages/devcmd/src/from-cli/index.ts [hunk 8]
```diff
@@ -23,6 +25,20 @@ export function run(...args: string[]) {
...
 }
 
+export async function runReserved(cmd: string) {
+  printDevcmdHeader();
+  process.stdout.write("\n");
+  assertInDevCmdsDir();
+  assertReservedCmdExists(cmd);
+
+  try {
+    const cmdFn = getReservedCommand(cmd);
```
Comment (lehnerpat) [inline packages/devcmd/src/from-cli/index.ts:43]: to expand on my comment above, is there a reason why we separate that `cmd` is available from actually retrieving the associated `cmdFn`?

`getReservedCommand` could just throw or return null if the command doesn't exist, right?

File: packages/devcmd-cli/src/index.ts [hunk 9]
```diff
@@ -73,6 +73,19 @@ async function startProcess(command: string, args: Array<string>, dirPath: strin
...
+  if (args.length > 0) {
+    const cmdName = args[0].trim();
+
+    if (cmdName.length > 2 && cmdName.indexOf("--") === 0) {
+      try {
+        await startProcess("node", ["-e", `require('devcmd/from-cli').runReserved('${cmdName.slice(2)}')`], dirPath);
+      } catch (err) {
+        err instanceof Error ? abort(err.stack ?? err.message) : process.exit(1);
+      }
+      process.exit(0);
```
Comment (lehnerpat) [inline packages/devcmd-cli/src/index.ts]: you can just `return` here, that will exit devcmd successfully :)

File: packages/devcmd-cli/src/index.ts [hunk 10]
```diff
@@ -73,6 +73,19 @@ async function startProcess(command: string, args: Array<string>, dirPath: strin
...
   const [, , ...args] = process.argv;
 
+  if (args.length > 0) {
+    const cmdName = args[0].trim();
+
+    if (cmdName.length > 2 && cmdName.indexOf("--") === 0) {
+      try {
+        await startProcess("node", ["-e", `require('devcmd/from-cli').runReserved('${cmdName.slice(2)}')`], dirPath);
+      } catch (err) {
+        err instanceof Error ? abort(err.stack ?? err.message) : process.exit(1);
```
Comment (lehnerpat) [inline packages/devcmd-cli/src/index.ts]: I was about to ask why we don't use `abort` or emit any message when `err` isn't an `Error`, but then I saw we do the same thing when starting a regular command below 🤔

I think we should change this (in both code paths). feel free to split this to a separate ticket/PR though if you want.

File: packages/devcmd-cli/src/index.ts [hunk 11]
```diff
@@ -73,6 +73,19 @@ async function startProcess(command: string, args: Array<string>, dirPath: strin
 async function runInDevCmdsDir(dirPath: string): Promise<void> {
   const [, , ...args] = process.argv;
 
+  if (args.length > 0) {
+    const cmdName = args[0].trim();
+
+    if (cmdName.length > 2 && cmdName.indexOf("--") === 0) {
+      try {
+        await startProcess("node", ["-e", `require('devcmd/from-cli').runReserved('${cmdName.slice(2)}')`], dirPath);
```
Comment (lehnerpat) [inline packages/devcmd-cli/src/index.ts]: with this code, you can't pass any further arguments to the reserved command. This isn't an issue for the two reserved commands we have right now, but I'd prefer to minimize unnecessary changes to devcmd-cli down the line.

please include the rest of `args` and also pass them to `runReserved` -- probably best also do this as separate arguments like we do for regular commands below, otherwise you need to figure out how to quote-escape them correctly :D

Comment (lehnerpat) [inline packages/devcmd-cli/src/index.ts]: note that this will fail when `cmdName.slice(2)` contains a single quote (e.g. running `devcmd --hel'p`), with an error message that's probably not easy to understand for a user

File: dev_cmds/integration-tests/reserved-commands.ts [hunk 12]
```diff
@@ -0,0 +1,96 @@
...
+      return "success";
+    }
+  };
+
+  const testCases = [
+    { name: "Setup", fn: setup },
+    { name: "List available commands", fn: listLogsAvailableCommands },
+    { name: "Devcmd Help", fn: helpLogsHelpInformation },
+  ];
+  return { name: "ts-node-availability", testCases };
```
Comment (lehnerpat) [inline dev_cmds/integration-tests/reserved-commands.ts]: the name of this test group doesn't really fit ;)

File: dev_cmds/integration-tests/reserved-commands.ts [hunk 13]
```diff
@@ -0,0 +1,96 @@
...
+        "sh",
+        "-c",
+        ["cd /tmp/devcmd_test/single-package-json", `npx devcmd --list`].join(" && "),
+      ],
+    });
+
+    const expectedCmds = ["example_cmd", "fails_with_error", "parameter_example_cmd"];
+
+    expectedCmds.forEach((cmd) => {
+      if (!stdout.includes(cmd)) return "fail";
```
Comment (lehnerpat) [inline dev_cmds/integration-tests/reserved-commands.ts]: some information about what caused the test to fail would be nice here :)

**Review by lehnerpat — CHANGES_REQUESTED** [review]
Thanks for getting started on this!

This already looks pretty good, but I've added some feedback :)

File: packages/devcmd-cli/src/index.ts (hunk 11 above)
Comment (lieberlois) [reply packages/devcmd-cli/src/index.ts]: True @PatrickLehnerXI !

Unfortunately, its pretty tricky calling commands like "--help" because you obviously want to avoid the node --help call 😆 do you have an idea how to "TODO: refactor this!" without the node --help problem? :) 

image

Comment (lehnerpat) [reply packages/devcmd-cli/src/index.ts]: Ahhh right, I hadn't realized that issue would of course affect this call as well. 

for any other readers: just like calling `devcmd --help` is a problem because it would trigger `node --version` before these changes, even with this `runReserved` call we could run into the same issue if the user tries `node --list --help`.

@lieberlois, I hadn't thought of this before, but we can probably side-step this entire issue by passing the [double-dash option (`--`)](https://nodejs.org/api/cli.html#cli_1) in the args list to node at the right place.
The double-dash option is a common feature of many *nix CLI programs to signal the "end of options", i.e. all arguments after the double dash argument are not interpreted as options to the command itself.

So in our case, we could do something like the following:

```ts
await startProcess(
  "node", 
  [
    "-e", 
    `require('devcmd/from-cli').run(...process.argv.slice(1))`, 
    "--",      // this is new
    ...args], 
  dirPath);
```

this might even make the `runReserved` variant obsolete altogether (because we can do the whole check for "is the first argument `--help` inside the devcmd package instead of here)

File: packages/devcmd/src/utils/get_reserved_command.ts (hunk 1 above)
Comment (lieberlois) [reply packages/devcmd/src/utils/get_reserved_command.ts]: Moved the get_reserved_commands file and removed barrel exports

File: packages/devcmd/src/utils/get_reserved_command.ts (hunk 2 above)
Comment (lieberlois) [reply packages/devcmd/src/utils/get_reserved_command.ts]: Done :) good idea

File: packages/devcmd/src/reserved-cmds/list.ts (hunk 4 above)
Comment (lieberlois) [reply packages/devcmd/src/reserved-cmds/list.ts]: I decided to use the node internal ```import { promises as fs } from "fs"``` implementation which worked great :)

File: packages/devcmd/src/reserved-cmds/list.ts (hunk 5 above)
Comment (lieberlois) [reply packages/devcmd/src/reserved-cmds/list.ts]: Added the following check within the forEach call:

```typescript
if (ALLOWED_FILE_TYPES.includes(fileType.toLowerCase())) {
  console.log(fileName);
}
```

The constant ALLOWED_FILE_TYPES is currently set to this:
```typescript
ALLOWED_FILE_TYPES = [".js", ".ts"];
```

File: packages/devcmd-cli/src/index.ts (hunk 10 above)
Comment (lieberlois) [reply packages/devcmd-cli/src/index.ts]: I would suggest doing this in a seperate ticket because error handling is a big thing in devcmd and can probably be improved overall!

File: packages/devcmd-cli/src/index.ts (hunk 11 above)
Comment (lieberlois) [reply packages/devcmd-cli/src/index.ts]: Exactly what I had in mind aswell 👍 

This now works properly:

```sh
node ➜ /workspaces/devcmd/dev (fix/30-help-list) $ yarn devcmd --help
yarn run v1.22.5
$ /workspaces/devcmd/dev/node_modules/.bin/devcmd --help
devcmd v0.0.8
Usage: devcmd <task>
Use devcmd --list to show available tasks.
Done in 0.21s.
node ➜ /workspaces/devcmd/dev (fix/30-help-list) $ yarn devcmd example_cmd
yarn run v1.22.5
$ /workspaces/devcmd/dev/node_modules/.bin/devcmd example_cmd
devcmd v0.0.8: cmd "example_cmd"
Example command for single-package-json example
Starting process: "node" ["-v"]
v12.22.4
Process "node" exited successfully.
Beginning parallel execution of 2 processes...
<nodeVersion> Starting process: "node" ["-v"]
<npmVersion> Starting process: "npm" ["--version"]
<nodeVersion> v12.22.4
<nodeVersion> Process "node" exited successfully.
<npmVersion> 6.14.14
<npmVersion> Process "npm" exited successfully.
Finished parallel execution.
Done in 5.10s.
```

Comment (lieberlois) [reply packages/devcmd-cli/src/index.ts]: This was merged with the normal runInDevCmdsDir function so this comment is probably obsolete now - right?

The usage you were referring to doesnt work anyways, at least not in ZSH bash
image

File: dev_cmds/integration-tests/reserved-commands.ts (hunk 12 above)
Comment (lieberlois) [reply dev_cmds/integration-tests/reserved-commands.ts]: It seems like this file was ~~copied~~ inspired by the other test group 😉

File: dev_cmds/integration-tests/reserved-commands.ts (hunk 13 above)
Comment (lieberlois) [reply dev_cmds/integration-tests/reserved-commands.ts]: Increased verbosity to the failing part of the test

File: packages/devcmd/src/reserved-cmds/list.ts (hunk 6 above)
Comment (lieberlois) [reply packages/devcmd/src/reserved-cmds/list.ts:8]: Youre right! Added the cwd to the console output 😄

**Review by lenaxus — COMMENTED** [review]
Your changes look good to me. But when trying to run the  --list task I have no success. I pulled the status of your PR. Reopened it in Container in VSCode, build it and then started the setup-dev. 

But with the --help command I get the NODE-specific help and with list, I get e.g. this error output: 
image

I am not sure if this problem exists because of my EPERM-Error which I had for the local dev development at the beginning. But maybe you have an idea what I am doing wrong?

**Comment by lieberlois** [comment]
@lenaxus I was not able to reproduce the error you just posted. For me everything works in a clean devcontainer:

image

File: packages/devcmd-cli/src/index.ts (hunk 10 above)
Comment (lehnerpat) [reply packages/devcmd-cli/src/index.ts]: sounds good, please create an issue for this if there isn't one already :)

File: packages/devcmd/src/from-cli/index.ts [hunk 14]
```diff
@@ -4,31 +4,37 @@ import { gray, bold, red, reset } from "kleur/colors";
...
+
+  if (scriptName.length > 2 && scriptName.indexOf("--") === 0) {
+    await runReserved(scriptName.slice(2), ...scriptArgs);
+  } else {
+    await runDevcmd(scriptName, ...scriptArgs);
+  }
+}
+
+async function runDevcmd(scriptName: string, ...scriptArgs: string[]) {
   findAndRunScript(process.cwd(), scriptName, scriptArgs).catch((reason) => {
```
Comment (lehnerpat) [inline packages/devcmd/src/from-cli/index.ts]: minor: this function now swallows the inner promise (since it's not awaited). That still works as intended for the current usage, but the outer async/await might be slightly misleading. it would be great if you could rewrite the content of this function to await the `findAndRunScript` call and use a try-catch block for error handling instead of `.catch()` :)

File: packages/devcmd/src/reserved-cmds/list.ts [hunk 15]
```diff
@@ -1,24 +1,28 @@
...
-        const fileName = f.slice(0, f.lastIndexOf("."));
-        console.log(fileName);
+        const lastDotIndex = f.lastIndexOf(".");
+
+        const fileName = f.slice(0, lastDotIndex);
+        const fileType = f.slice(lastDotIndex);
+
+        if (ALLOWED_FILE_TYPES.includes(fileType.toLowerCase())) {
+          console.log(fileName);
+        }
```
Comment (lehnerpat) [inline packages/devcmd/src/reserved-cmds/list.ts]: you can use `basename()` and `extname()` from Node's [`path` module](https://nodejs.org/api/path.html) for extracting the file's basename and extension :) (or the `parse()` function from the same module, if you want)

File: packages/devcmd/src/reserved-cmds/list.ts [hunk 16]
```diff
@@ -1,24 +1,28 @@
...
       });
     } else {
```
Comment (lehnerpat) [inline packages/devcmd/src/reserved-cmds/list.ts:20]: this else case may not be hit even if the loop above doesn't print anything (e.g. the `dev_cmds` dir contains only a `README.md` file and nothing else), which might be confusing. 

you could fix this by checking/extracting the filetype before deciding whether to print anything (e.g. using `.filter()` and/or `.map()` on `files` instead of just an if-statement inside the loop)

**Review by lehnerpat — COMMENTED** [review]
progress!

thanks for your continued work on this and sorry for my late review.
I still found some small things, but this is coming along nicely :)

**Comment by lehnerpat** [comment]
@lenaxus @lieberlois, I won't be able to re-test this until next weekend, but I think you should try to look into @lenaxus's issues with testing these changes. The problem might be in the dev setup (either @lenaxus's local setup or the dev instructions), but we should try to make this more reliable to set up if it's not a localized problem.

I suggest you two take a look at the problem together, but it would be great if you could post an update here if you find out what the cause was :)

otherwise, @lenaxus please try to re-setup your local devcmd environment, and include any errors you get during setup in a comment (here or maybe in a new issue)

File: packages/devcmd/src/from-cli/index.ts (hunk 14 above)
Comment (lieberlois) [reply packages/devcmd/src/from-cli/index.ts]: Good catch!

File: packages/devcmd/src/reserved-cmds/list.ts (hunk 16 above)
Comment (lieberlois) [reply packages/devcmd/src/reserved-cmds/list.ts:20]: Didnt think of that, thanks ^^

The files array is now being filtered immediatly

**Comment by lieberlois** [comment]
@lehnerpat Sorry for only adding those changes now, I didnt have much spare time recently. I adapted the code to a) no longer swallow the promise you described and b) properly list the available commands.

@lenaxus Please create an issue and describe your changes with the dev setup, I will try to reproduce it and fix it in a separate PR :)

**Comment by lenaxus** [comment]
@lieberlois @lehnerpat Just for your information why I am not creating a new issue with my problem that this feature was not working at my computer. I was not able to reproduce it and now all of the features of this PR (and the rest ;)) works fine. I am sorry for the false alarm.

File: packages/devcmd/src/from-cli/index.ts (hunk 8 above)
Comment (PatrickLehnerXI) [reply packages/devcmd/src/from-cli/index.ts:43]: I'll fix this myself and then will manually merge this PR :)

**Review by PatrickLehnerXI — APPROVED** [review]
